version: '3.1'

services:
  keycloak:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
  postgres:
    container_name: postgresDb
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
