spring:
  application:
    name: ebay-clone
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 12345
server:
  port: 8181
logging:
  level:
    org.springframework.security: DEBUG

keycloak:
  realm: master
  auth-server-url: http://localhost:8080
  resource: ebay-cli
  public-client: true